### ISSUE TITLE
yadisk-direct failed

### ISSUE THREAD

**Issue by godblesshugh** [wldhx/yadisk-direct#1]
```
Traceback (most recent call last):
  File "/usr/local/bin/yadisk-direct", line 9, in <module>
    load_entry_point('wldhx.yadisk-direct==0.0.6', 'console_scripts', 'yadisk-direct')()
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 351, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2363, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2088, in load
    entry = __import__(self.module_name, globals(),globals(), ['__name__'])
  File "/usr/local/lib/python2.7/dist-packages/wldhx/yadisk_direct/main.py", line 9
    def get_real_direct_link(sharing_link: str) -> str:
                                         ^
SyntaxError: invalid syntax
```

**Comment by wldhx** [comment]
This package is Python 3 only. How did you install it?

**Comment by godblesshugh** [comment]
there's python3 & python2 in my ubuntu, and i run this:
```
sudo apt-get install python3-pip
pip3 install wldhx.yadisk-direct
yadisk-direct url
```

using `pip install wldhx.yadisk-direct` report error:
```
Command /usr/bin/python -c "import setuptools, tokenize;__file__='/tmp/pip-build-PhUPdj/wldhx.yadisk-direct/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-iHeH4_-record/install-record.txt --single-version-externally-managed --compile failed with error code 1 in /tmp/pip-build-PhUPdj/wldhx.yadisk-direct
Storing debug log for failure in /home/user/.pip/pip.log
```

**Comment by godblesshugh** [comment]
solved.
the default command `python` is `python2`, using `ln -s` to replace `/usr/bin/python` with `/usr/bin/python3.4` make it work.

**Comment by wldhx** [comment]
I'm glad it worked for you; it's weird you had that problem though as the script explicitly specifies py3 to be run by itself: https://github.com/wldhx/yadisk-direct/blob/master/wldhx/yadisk_direct/main.py#L1.

**Comment by godblesshugh** [comment]
dont know why, but those fix method works for me, thanks for this excellent tool.

**Comment by wldhx** [comment]
Okay, I suppose I'll leave further research into this until after someone else has a similar problem.

I'm glad it's useful to you :)

**Comment by godblesshugh** [comment]
OK, thanks again.
